proxy:
  image: proxy:1.0
  links:
    - identidock
  ports:
    - "80:80"
  environment:
    - NGINX_HOST=3.90.12.121
    - NGINX_PROXY=http://identidock:9090

identidock:
  image: amouat/identidock:1.0
  environment:
    ENV: PROD
  links:
    - dnmonster
    - redis

dnmonster:
  image: amouat/dnmonster:1.0

redis:
  image: redis:3.0

